import type { Listing, KpiData } from "./types";
import type { SourceFixture } from "../lib/pipeline/types";

const yesterday = "2026-05-15T22:00:00Z";

export const listings: Listing[] = [
  {
    id: "1",
    name: "Nila Kitchen",
    category: "Restaurant",
    tier: "A",
    address: "Kantstraße 42, 10625 Berlin",
    phone: "+49 30 1234567",
    email: "info@nilakitchen.de",
    website: "http://localhost:5174",
    opening_hours: "Mon–Sun 11:00–22:00",
    lastRunAt: yesterday,
    status: "auto_applied",
    confidence: 0.91,
    changedFields: ["opening_hours"],
    emailSent: false,
    live: true,
  },
  {
    id: "2",
    name: "Bäckerei Müller",
    category: "Bakery",
    tier: "A",
    address: "Hauptstraße 12, 80331 München",
    phone: "+49 89 9876543",
    email: "hallo@baeckerei-mueller.de",
    website: "https://baeckerei-mueller.de",
    opening_hours: "Mon–Sat 06:00–18:00",
    lastRunAt: yesterday,
    status: "needs_review",
    confidence: 0.71,
    changedFields: ["phone"],
    emailSent: true,
  },
  {
    id: "3",
    name: "Zahnarztpraxis Dr. Schmidt",
    category: "Dentist",
    tier: "A",
    address: "Friedrichstraße 88, 10117 Berlin",
    phone: "+49 30 5554321",
    email: "praxis@dr-schmidt.de",
    website: "https://zahnarzt-schmidt-berlin.de",
    opening_hours: "Mon–Fri 08:00–17:00",
    lastRunAt: yesterday,
    status: "auto_applied",
    confidence: 0.93,
    changedFields: ["phone"],
    emailSent: false,
  },
  {
    id: "4",
    name: "Friseur Haarwerk",
    category: "Hair Salon",
    tier: "B",
    address: "Schanze 7, 20357 Hamburg",
    phone: "+49 40 3216547",
    email: "info@haarwerk-hamburg.de",
    website: "https://haarwerk-hamburg.de",
    opening_hours: "Tue–Sat 09:00–19:00",
    lastRunAt: yesterday,
    status: "needs_review",
    confidence: 0.63,
    changedFields: ["phone", "website"],
    emailSent: true,
  },
  {
    id: "5",
    name: "Hotel Goldener Adler",
    category: "Hotel",
    tier: "A",
    address: "Marienplatz 3, 80331 München",
    phone: "+49 89 7654321",
    email: "reservierung@goldener-adler.de",
    website: "https://goldener-adler.de",
    opening_hours: "24/7",
    lastRunAt: yesterday,
    status: "auto_applied",
    confidence: 0.88,
    changedFields: ["opening_hours"],
    emailSent: false,
  },
  {
    id: "6",
    name: "Apotheke am Bahnhof",
    category: "Pharmacy",
    tier: "B",
    address: "Bahnhofstraße 19, 20099 Hamburg",
    phone: "+49 40 1122334",
    email: "info@apotheke-bahnhof-hh.de",
    website: "https://apotheke-bahnhof-hh.de",
    opening_hours: "Mon–Fri 08:00–20:00, Sat 09:00–14:00",
    lastRunAt: yesterday,
    status: "source_offline",
    confidence: null,
    changedFields: [],
    emailSent: false,
  },
  {
    id: "7",
    name: "Autohaus Schneider",
    category: "Car Dealership",
    tier: "B",
    address: "Industriestraße 55, 70376 Stuttgart",
    phone: "+49 711 8899001",
    email: "verkauf@autohaus-schneider.de",
    website: "https://autohaus-schneider-stuttgart.de",
    opening_hours: "Mon–Fri 09:00–18:00, Sat 10:00–15:00",
    lastRunAt: yesterday,
    status: "needs_review",
    confidence: 0.55,
    changedFields: ["email"],
    emailSent: true,
  },
  {
    id: "8",
    name: "Buchhandlung Lesen & Leben",
    category: "Bookstore",
    tier: "B",
    address: "Rüttenscheider Str. 44, 45128 Essen",
    phone: "+49 201 4455667",
    email: "kontakt@lesen-leben.de",
    website: "https://lesen-leben.de",
    opening_hours: "Mon–Sat 10:00–19:00",
    lastRunAt: yesterday,
    status: "auto_applied",
    confidence: 0.87,
    changedFields: ["opening_hours"],
    emailSent: false,
  },
  {
    id: "9",
    name: "Neo Tokyo GmbH i.G.",
    category: "Technology",
    tier: "A",
    address: "Unter den Linden 10, 10117 Berlin",
    phone: "+49 30 7654321",
    email: "hello@neo-tokyo.de",
    website: "https://neo-tokyo.de",
    opening_hours: "Mon–Fri 09:00–18:00",
    lastRunAt: yesterday,
    status: "needs_review",
    confidence: 0.72,
    changedFields: ["phone", "opening_hours"],
    emailSent: true,
  },
];

export const seedKpi: KpiData = {
  entriesChecked: 234,
  autoUpdates: 4,
  needsReview: 3,
  updatesToday: 7,
};

export const sourceFixtures: SourceFixture[] = [
  {
    listingId: "1",
    sitemap_lastmod_changed: false,
    etag_old: "abc123",
    etag_new: "def456",
    last_modified_old: "Wed, 14 May 2026 10:00:00 GMT",
    last_modified_new: "Wed, 14 May 2026 10:00:00 GMT",
    source_html: `<p data-field="phone">+49 30 9999888</p><p data-field="opening_hours">Mon–Sun 12:00–23:00</p>`,
  },
  {
    listingId: "2",
    sitemap_lastmod_changed: true,
    etag_old: "e1",
    etag_new: "e1",
    last_modified_old: "Wed, 14 May 2026 10:00:00 GMT",
    last_modified_new: "Wed, 14 May 2026 10:00:00 GMT",
    source_html: `<div class="contact-info">Rufnummer: 089/9999999 (Zentrale)</div>`,
  },
  {
    listingId: "3",
    sitemap_lastmod_changed: false,
    etag_old: "z1",
    etag_new: "z2",
    last_modified_old: "Wed, 14 May 2026 10:00:00 GMT",
    last_modified_new: "Wed, 14 May 2026 10:00:00 GMT",
    source_html: `<p data-field="phone">+49 30 8888321</p>`,
  },
  {
    listingId: "4",
    sitemap_lastmod_changed: true,
    etag_old: "h1",
    etag_new: "h1",
    last_modified_old: "Wed, 14 May 2026 10:00:00 GMT",
    last_modified_new: "Wed, 14 May 2026 10:00:00 GMT",
    source_html: `<span class="tel">+49 40 3333333</span>`,
  },
  {
    listingId: "5",
    sitemap_lastmod_changed: false,
    etag_old: "ga1",
    etag_new: "ga2",
    last_modified_old: "Wed, 14 May 2026 10:00:00 GMT",
    last_modified_new: "Wed, 14 May 2026 10:00:00 GMT",
    source_html: `<p data-field="opening_hours">Mon–Sun 00:00–23:59</p>`,
  },
  {
    listingId: "6",
    sitemap_lastmod_changed: false,
    etag_old: "ap1",
    etag_new: "offline",
    last_modified_old: "Wed, 14 May 2026 10:00:00 GMT",
    last_modified_new: "Wed, 14 May 2026 10:00:00 GMT",
    source_html: "",
  },
  {
    listingId: "7",
    sitemap_lastmod_changed: false,
    etag_old: "as1",
    etag_new: "as2",
    last_modified_old: "Wed, 14 May 2026 10:00:00 GMT",
    last_modified_new: "Wed, 14 May 2026 10:00:00 GMT",
    source_html: `<p>Kontakt: info@schneider-autos.de</p>`,
  },
  {
    listingId: "8",
    sitemap_lastmod_changed: false,
    etag_old: "bl1",
    etag_new: "bl2",
    last_modified_old: "Wed, 14 May 2026 10:00:00 GMT",
    last_modified_new: "Wed, 14 May 2026 10:00:00 GMT",
    source_html: `<p data-field="opening_hours">Mon–Sat 10:00–20:00</p>`,
  },
  {
    listingId: "9",
    sitemap_lastmod_changed: true,
    etag_old: "nt1",
    etag_new: "nt2",
    last_modified_old: "Wed, 14 May 2026 10:00:00 GMT",
    last_modified_new: "Thu, 15 May 2026 09:00:00 GMT",
    source_html: `<span class="tel">+49 30 9999777</span><p>Öffnungszeiten: Mo–Fr 10:00–19:00</p>`,
  },
];
